[package]
name = "quantum-core"
version = "0.1.3"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "0.4.2"
num-traits = "0.2.19"

[dev-dependencies] 
itertools = "0.10.5"
