[build]
rustflags = ["-C", "target-cpu=x86-64-v3"]

[net]
git-fetch-with-cli = true

[profile.release]
debug = true

[profile.bench]
debug = true

[alias]
clippy-all = "clippy --workspace --all-targets --all-features -- -D clippy::pedantic"
doc-binar = "doc --open --no-deps --package binar"