[build]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[net]
git-fetch-with-cli = true

[profile.release]
debug = true

[profile.bench]
debug = true

[alias]
clippy-all = "clippy --workspace --all-targets --all-features -- -D clippy::pedantic"
doc-binar = "doc --open --no-deps --package binar"